### ISSUE TITLE
Criar alertas de pendências

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-extensao#153]
Criar alertas de pendências no menu: ações aguardando parecer, ações aguardando resolução de pendências.

**Comment by gustavoaires** [comment]
Ações aguardando homologação conta como pendências? Quais os tipos de pendências?

**Comment by gustavoaires** [comment]
/**
	 * Retorna todas as ações que estão aguardando parecer técnico ou do relator de um determinado parecerista ou relator
	 * e também as que estão aguardando as resoluções de pendências
	 */
	List<AcaoExtensao> findAcoesAguardandoParecer(Pessoa parecerista);

Esse método aqui já retorna tudo?

**Comment by gustavoaires** [comment]
Devem ser exibidas as ações do coordenador logado que estão com essas pendências?

**Comment by thalita-moura** [comment]
São três categorias de notificações:

- Direção: mostrar pendências de aguardando parecerista técnico, de aguardando relator e de aguardando homologação;
- Parecerista e Relator: mostrar pendência de aguardando parecer técnico e parecer do relator;
- Coordenador: mostrar resolvendo pendências do parecer e do relator.

**Comment by gustavoaires** [comment]
***************************
APPLICATION FAILED TO START
***************************

Description:

Field acaoExtensaoService in ufc.quixada.npi.gpa.controller.AcaoExtensaoController required a bean of type 'ufc.quixada.npi.gpa.service.AcaoExtensaoService' that could not be found.


Action:

Consider defining a bean of type 'ufc.quixada.npi.gpa.service.AcaoExtensaoService' in your configuration.

**Comment by lucasvss** [comment]
As notificações estão sendo exibidas conforme as especificações.
