### ISSUE TITLE
Informar quantidade de bolsas recebidas

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-extensao#156]
Informar quantidade de bolsas recebidas.

**Comment by lucasvss** [comment]
Ao exibir a página de detalhes de uma certa ação é exibido a quantidade de bolsas recebidas conforme o esperado.

**Comment by virginiafarias** [comment]
Essa atividade é para permitir que o coordenador possa informar a quantidade de bolsas recebidas, após a ação ser aprovada e enquanto a ação estiver em andamento.

**Comment by thalita-moura** [comment]
Verificar comentários da revisão de código.

**Comment by lucasvss** [comment]
Ao exibir a página de detalhes de uma ação do coordenador com status APROVADA e que ainda está ativa é exibido o botão para adicionar o número de bolsas que o coordenador recebeu para aquela a ação.

O número de bolsas que o coordenador fornece é cadastrado e exibido na página de detalhes da ação.
