### ISSUE TITLE
Incluir/excluir/visualizar parceria externa

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-extensao#157]
Incluir/excluir/visualizar parceria externa

**Comment by virginiafarias** [comment]
**US06 – Incluir parceria externa**
Eu como Servidor gostaria de incluir uma parceria externa a uma ação de extensão já cadastrada para identificar quem são os parceiros da ação.
* Se o parceiro externo já existir no sistema, realizar apenas um vínculo com a parceria, adicionando o restante das informações da parceria: formas de inserção (gera demanda, participa na definição de ações, fornece instalações e/ou equipamentos, participa de financiamento, outras formas). Caso contrário, permitir também cadastrar o parceiro com as seguintes informações: nome da instituição e tipo de instituição.
* As formas de inserções devem ser opções que podem ou não ser selecionadas.
* Todos os campos são de preenchimento obrigatório. A forma de inserção deve ter pelo menos um dos itens selecionado.
* Caso a opção de inserção outras formas seja selecionada, solicitar o preenchimento da descrição da forma de inserção.
* Deve ser permitida a escolha de apenas uma opção para o tipo de instituição.
* Não permitir a inclusão após o encerramento da ação.

**US07 – Excluir parceria externa**
Eu como Servidor gostaria de excluir uma parceria externa de uma ação de extensão cadastrada.
* Solicitar a confirmação da exclusão da parceria.
* Não permitir a exclusão após o encerramento da ação.

**US08 – Visualizar parcerias externas**
Eu como Servidor desejo visualizar todas a parcerias externas de uma determinada ação de extensão.
* Exibir uma lista de todas as parcerias vinculadas à ação mostrando todas as informações da parceria na página de detalhe da ação.

**Comment by lucasvss** [comment]
A inclusão da parceria está sendo realizada conforme o esperado, mas no momento só é possível adicionar parcerias nas ações que são NOVAS.

Uma melhoria que pode ser realizada em relação a inclusão de parcerias é que não permita adicionar a parceria com a opção outras formas só com espaços.

----------------------------------------------------------------------------------------------------------------------------------

A exclusão está sendo realizada mas não é pedido uma confirmação para continuar com a exclusão da parceria. A opção de exclusão também só é mostrada quando a ação do coordenador é NOVA.

-----------------------------------------------------------------------------------------------------------------------------------

Na página de detalhes da ação está sendo exibida as parcerias que foram adicionadas para aquela ação conforme o esperado.

**Comment by lucasvss** [comment]
As melhorias foram implementadas e as funcionalidades de incluir, visualizar e e excluir uma parceria estão conforme o especificado.
