### ISSUE TITLE
Incluir novo participante

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-extensao#158]
Incluir novo participante na equipe de trabalho.

**Comment by lucasvss** [comment]
Inclusão de um novo participante está sendo realizada respeitando as regras para efetuar o cadastro de um participante conforme o esperado.

Melhorias que podem ser feitas:

1ª - Não exibir o botão "Novo Participante" na ação que não é do servidor logado.

![melhoria.png](https://zube.io/files/npi-ufc-qxd/f18435233eab1a3e4cbfa1c77e842130.png)

2ª - Ao tentar adicionar o mesmo participante que já foi adicionado para aquela ação é exibido uma mensagem na url, a melhoria seria exibir um alert para informar a mensagem.

![melhoria2.png](https://zube.io/files/npi-ufc-qxd/e690864459e72b9d20cb13dc9da5dc07.png)

3ª - Ao adicionar um novo participante a página é recarregada e é mostrado os dados do participante que foi cadastrado, seria ideal emitir um alert informando que o particpante foi adicionado.

**Comment by virginiafarias** [comment]
Sugestões:
* Colocar dois botões "Adicionar Participante" e "Adicionar Bolsista" já na listagem da equipe de trabalho, pra não precisar abrir um modal só pra realizar essa escolha.
* Ajustar a organização do campos no formulário pra deixar o servidor ao lado da escolha da função, nome da instituição ao lado da escolha da instituição e o restante dos campos em 2 colunas.
* Alinhar os botões à direita pra manter o padrão do restante do sistema.

**Comment by virginiafarias** [comment]
**US09 – Adicionar participante à equipe de trabalho**

Eu como Servidor gostaria de adicionar um participante à equipe de trabalho de uma ação de extensão da qual sou coordenador.
* A participação deve conter as seguintes informações: função, participante, instituição, carga horária semanal, data de início e data de término.
* Todos os campos são de preenchimento obrigatório.
* As opções de função são: Técnico Administrativo, Docente e Outra.
* Ao selecionar a opção Técnico Administrativo, mostrar somente os servidores com essa função no campo Servidor, assim como para a opção Docente. Mostrar a lista de servidores em ordem alfabética. Ao selecionar a opção Outra, permitir que o usuário preencha os campos de nome, cpf e função ao invés de escolher o Servidor de uma lista.
* As opções de instituição são: Universidade Federal do Ceará, Outra Instituição de Ensino Superior e Outra Instituição.
* Ao selecionar a opção Outra Instituição de Ensino Superior ou Outra Instituição, solicitar o preenchimento do campo de Nome da Instituição.
* A carga horária deve ter no mínimo 4h e no máximo 16h.
* Os campos data de início e data de término devem ter como valor default o período da ação, permitindo que o usuário possa alterar essas datas dentro do limite de duração da ação.
* A inclusão só poderá ser realizada pelo coordenador da ação quando a ação estiver nos seguintes status: NOVA, RESOLVENDO PENDÊNCIAS DO PARECER, RESOLVENDO PENDÊNCIAS DO RELATO e APROVADA. Não permitir a inclusão quando a ação estiver encerrada.
