### ISSUE TITLE
Aprimorar layout da página "Minhas extensões"

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-extensao#159]
Aplicar o mesmo layout da página de listagem de extensão na página "Minhas extensões".

**Comment by lucasvss** [comment]
Os cards estão redirecionando para suas respectivas tabelas conforme o esperado. O que deve ser refeito é o nome que os cards contém.

Melhorias.

1ª Em vez do nome do primeiro card ser "EM TRAMITAÇÃO" mudar para "MINHAS AÇÕES".
2ª Em vez do nome do segundo card ser "EM ANDAMENTO" mudar para "AGUARDANDO PARECER".
3ª Em vez do nome do terceiro card ser "ENCERRADAS" mudar para "PARECERES EMITIDOS"


![melhoria4.png](https://zube.io/files/npi-ufc-qxd/4583dca32928e861998a8f5910cb4e0f.png)

**Comment by virginiafarias** [comment]
** US05 – Visualizar listagem de todas as ações de extensão vinculadas ao usuário logado**

Eu como Servidor gostaria de visualizar uma listagem com todas as minhas ações de extensão.

* A listagem deve conter um resumo da ação da ação de extensão com as seguintes informações: vínculo, título, coordenador, período de início e término e status.
* O título deve conter um link para a página de detalhe da respectiva ação.
* Permitir ordenar a listagem por qualquer um dos valores mostrados.
Separar as ações em grupos:
* Grupo 1: ações em que o usuário é coordenador ou participante.
* Grupo 2: ações em que o usuário é é parecerista/relator e estão aguardando parecer.
* Grupo 3: ações em que o usuário é parecerista/relator e já emitiu o parecer.
* O vínculo só deve ser exibido nas ações do grupo 1.
* O coordenador só deve ser exibido nas ações dos grupos 1 e 2.
