### ISSUE TITLE
Atribuir/alterar parecerista/relator e emitir parecer

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-extensao#161]
Atribuir/alterar parecerista/relator e emitir parecer.

**Comment by julioserafim** [comment]
- Atribuição Parecerista/Relator OK

**Comment by lucasvss** [comment]
A atribuição de um parecerista está sendo realizada conforme o esperado. Mas algumas melhorias devem ser realizadas.

1ª - Não deve ser permitido atribuir um prazo para emissão do parecer só com espaços em branco.

![melhoria7.png](https://zube.io/files/npi-ufc-qxd/496267bc0bef044a050f1caeb3f9a201.png)

2ª - Não deve ser permitido preencher o prazo para emissão do parecer com caracteres especiais ou letras pois se tentarmos atribuir um parecerista com um prazo com esses valores é emitido uma página de erro.

![melhoria6.png](https://zube.io/files/npi-ufc-qxd/227dd36488ce9d50834e6caff1542c7d.png)

3ª - Quando é adicionado um novo parecerista o sistema está redirecionando para uma página que não existe.

![melhoria8.png](https://zube.io/files/npi-ufc-qxd/68a49aaa2c823611326a336127bea61b.png)

--------------------------------------------------------------------------------------------------------------------------------

A alteração dos dados do parecerista técnico está sendo realizada conforme a especificação. Mas algumas melhorias devem ser realizadas.

1ª - Não deve ser permitido atribuir um prazo para emissão do parecer só com espaços em branco quando for realizada a alteração.

![melhoria10.png](https://zube.io/files/npi-ufc-qxd/73cd58cfa7f4e3c95dff0bc40d0f9de6.png)

2ª -  Não deve ser permitido preencher o prazo para emissão do parecer com caracteres especiais ou letras pois se tentarmos alterar um parecerista com um prazo com esses valores é emitido uma página de erro.

![melhoria6.png](https://zube.io/files/npi-ufc-qxd/227dd36488ce9d50834e6caff1542c7d.png)

3ª - Quando o parecerista é alterado o sistema está redirecionando para uma página que não existe.

![melhoria8.png](https://zube.io/files/npi-ufc-qxd/68a49aaa2c823611326a336127bea61b.png)

--------------------------------------------------------------------------------------------------------------------------------

A emissão de parecer técnico está funcionando corretamente como esperado só que está faltando o campo para adicionar o arquivo do parecer se o parecerista preferir adicionar um arquivo em vez de preencher o campo parecer.

![bug2.png](https://zube.io/files/npi-ufc-qxd/9f79c1fc8d445d830a14d8efc3ebb512.png)

É preciso também realizar algumas melhorias.

1ª - Ao emitir parecer o sistema redireciona para uma página que não existe.

![melhoria8.png](https://zube.io/files/npi-ufc-qxd/68a49aaa2c823611326a336127bea61b.png)

2ª - O sistema não deve permitir que o parecer seja só espaços.
 
![melhoria11.png](https://zube.io/files/npi-ufc-qxd/41dc23a955b10b433d3eb2cd518f7ee2.png)

--------------------------------------------------------------------------------------------------------------------------------

A atribuição de um parecerista relator está sendo realizada conforme o esperado. Mas algumas melhorias devem ser realizadas.

1ª - Não deve ser permitido atribuir um prazo para emissão do parecer só com espaços em branco.

![melhoria14.png](https://zube.io/files/npi-ufc-qxd/a0c424684932fa0446f9acc6bc8dad86.png)

2ª - Não deve ser permitido preencher o prazo para emissão do parecer com caracteres especiais ou letras pois se tentarmos atribuir um parecerista relator com um prazo com esses valores é emitido uma página de erro.

![melhoria12.png](https://zube.io/files/npi-ufc-qxd/7f81fe1db31da14cdfeaa4b99a67bde3.png)

3ª - Quando é adicionado um novo parecerista o sistema está redirecionando para uma página que não existe.

![melhoria13.png](https://zube.io/files/npi-ufc-qxd/e6ebcc9f507440bed4dca4e16ec56eba.png)

---------------------------------------------------------------------------------------------------------------------------------

A alteração dos dados do parecerista relator está sendo realizada conforme a especificação. Mas algumas melhorias devem ser realizadas.

1ª - Não deve ser permitido atribuir um prazo para emissão do parecer só com espaços em branco quando for realizada a alteração.

![melhoria10.png](https://zube.io/files/npi-ufc-qxd/73cd58cfa7f4e3c95dff0bc40d0f9de6.png)

2ª -  Não deve ser permitido preencher o prazo para emissão do parecer com caracteres especiais ou letras pois se tentarmos alterar um parecerista relator com um prazo com esses valores é emitido uma página de erro.

![melhoria6.png](https://zube.io/files/npi-ufc-qxd/227dd36488ce9d50834e6caff1542c7d.png)

3ª - Quando o parecerista é alterado o sistema está redirecionando para uma página que não existe.

![melhoria8.png](https://zube.io/files/npi-ufc-qxd/68a49aaa2c823611326a336127bea61b.png)

---------------------------------------------------------------------------------------------------------------------------------

A emissão de parecer do relator está funcionando corretamente como esperado só que está faltando o campo para adicionar o arquivo do parecer se o parecerista preferir adicionar um arquivo em vez de preencher o campo parecer.

![melhoria15.png](https://zube.io/files/npi-ufc-qxd/7639080787d913cd91deff8deee36900.png)

É preciso também realizar algumas melhorias.

1ª - Ao emitir parecer o sistema redireciona para uma página que não existe.

![melhoria13.png](https://zube.io/files/npi-ufc-qxd/e6ebcc9f507440bed4dca4e16ec56eba.png)

2ª - O sistema não deve permitir que o parecer seja só espaços.
 
![melhoria16.png](https://zube.io/files/npi-ufc-qxd/6f06811b7ae6d083cacc0b3538822409.png)

**Comment by lucasvss** [comment]
As funcionalidades estão conforme o especificado, só é preciso melhorar a interface.
