### ISSUE TITLE
Incluir novo bolsista

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-extensao#167]
Incluir novo bolsista na equipe de trabalho.

**Comment by lucasvss** [comment]
Ao tentar adicionar um bolsista na página de detalhas da ação, não é mostrado o botão de "Novo Participante" pois esse botão só é mostrado se uma ação tem status "NOVA" e para adicionar um bolsista a ação deve ter status "APROVADA", devido a isso não dar para testar a funcionalidade de adicionar um bolsista.
![melhoria3.png](https://zube.io/files/npi-ufc-qxd/9e5f2498ffd0a4f55751aefee3fb58a3.png)

**Comment by lucasvss** [comment]
Ao tentar adicionar um bolsista a uma ação a bolsa é adicionada ao banco mas o bolsista que foi selecionado para esse bolsa não é adicionado a bolsa, tendo em vista isso uma mensagem de erro é mostrada logo após a adição do bolsista pois não será exibido os detalhes do bolsista que deveria ter sido incluído.

  
![bug.png](https://zube.io/files/npi-ufc-qxd/b6de181f63abb4180f400d6fa6856241.png)

**Comment by virginiafarias** [comment]
**US14 – Adicionar bolsista à equipe de trabalho**

Eu como Servidor gostaria de adicionar um bolsista à equipe de trabalho de uma ação de extensão da qual sou coordenador.

* O bolsista deve conter as seguintes informações: função, aluno, carga horária semanal, data de início e data de término.
* Todos os campos são de preenchimento obrigatório.
* As opções de função são: Aluno Bolsista ou Aluno Voluntário.
* A carga horária deve ser de 16h.
* Os campos data de início e data de término devem ter como valor default o período da ação, permitindo que o usuário possa alterar essas datas dentro do limite de duração da ação.
* A inclusão só poderá ser realizada pelo coordenador da ação quando a ação estiver nos seguintes status: NOVA, RESOLVENDO PENDÊNCIAS DO PARECER, RESOLVENDO PENDÊNCIAS DO RELATO e APROVADA. Não permitir a inclusão quando a ação estiver encerrada.
* Só deve ser possível incluir Aluno Bolsista até o número limite de bolsas recebidas para a ação.

**Comment by lucasvss** [comment]
Bolsista está sendo adicionado a equipe de trabalho conforme o esperado.
