### ISSUE TITLE
Corrigir edição de ação de extensão

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/gpa-extensao#175]
* Mostrar o identificador sem opção de alteração.
* Não mostrar o campo de carga horária do coordenador.
* Permitir excluir o arquivo da ação.
* Permitir fazer upload de novo arquivo após a exclusão.
* O campo Programação não está sendo salvo ao selecionar modalidade curso ou evento.

**Comment by lucasvss** [comment]
A edição está sendo realizada conforme o esperado, o identificador está sem a opção de alteração, não é mostrado o campo de carga horária do coordenador, está sendo permitido a exclusão do arquivo da ação, está sendo permitido realizar upload de um novo arquivo após a exclusão do arquivo antigo e o campo programação está sendo salvo ao escolhe uma das opções de modalidade (Curso ou Evento).
