### ISSUE TITLE
Incluir opção de excluir ação na página de detalhe da ação

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/gpa-extensao#176]

**Comment by lucasvss** [comment]
O sistema não está exibindo o botão de excluir em uma ação NOVA que não é do coordenador e a exclusão da ação NOVA que o coordenador possui está sendo excluída conforme a especificação.

**Comment by thalita-moura** [comment]
Verificar alterações pedidas na revisão de código.

**Comment by julioserafim** [comment]
Ok
