### ISSUE TITLE
Remover participante/bolsista da equipe de trabalho

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/gpa-extensao#180]
**US10 – Remover participante ou bolsista da equipe de trabalho**

Eu como Servidor desejo remover um participante da equipe de trabalho de uma ação de extensão.
Solicitar a confirmação da exclusão do participante.

* Não permitir remover o coordenador da equipe de trabalho.
* A exclusão só poderá ser realizada pelo coordenador da ação quando a ação estiver nos seguintes status: NOVA, RESOLVENDO PENDÊNCIAS DO PARECER, RESOLVENDO PENDÊNCIAS DO RELATO e APROVADA. Não permitir a exclusão quando a ação estiver encerrada.

**Comment by lucasvss** [comment]
Está sendo permitido a exclusão do coordenador algo que não deveria ser permitido e quando a ação está encerrada mesmo assim é permitido a exclusão dos participantes.

**Comment by lucasvss** [comment]
Exclusão está sendo realizada conforme o especificado.
