### ISSUE TITLE
Alterar período de participação do participante ou bolsista da equipe de trabalho

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/gpa-extensao#182]
**US11 – Alterar período de participação do participante ou bolsista da equipe de trabalho**

Eu como Servidor gostaria de alterar o período de participação de um participante da equipe de trabalho de uma ação de extensão.

* Mostrar o nome do participante e função e os campos de data de início e data de término com os valores atuais, permitindo alterar apenas as datas dentro do limite do período da ação.
* A alteração só poderá ser realizada pelo coordenador da ação quando a ação estiver nos seguintes status: NOVA, RESOLVENDO PENDÊNCIAS DO PARECER, RESOLVENDO PENDÊNCIAS DO RELATO e APROVADA. Não permitir a alteração quando a ação estiver encerrada.

**Comment by lucasvss** [comment]
A alteração está sendo realizada conforme o esperado.
