### ISSUE TITLE
Enviar e-mail de notificação do parecer

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/gpa-extensao#183]
**US39 – Enviar e-mail de notificação do parecer**

Eu como Servidor desejo que seja enviado e-mail de notificação para o parecerista/relator para que os mesmos emitem seus pareceres.

* Deve ser enviado um e-mail informando ao parecerista/relator que o prazo para emissão do parecer se encerra em um dia.
* Se o status da ação for AGUARDANDO PARECER DO PARECERISTA, o e-mail deve ser enviado ao parecerista no prazo mencionado anteriormente.
* Se o status da ação for AGUARDANDO PARECER DO RELATOR, o e-mail deve ser enviado ao relator no prazo mencionado anteriormente.

**Comment by lucasvss** [comment]
Email está sendo enviado conforme o especificado.
