### ISSUE TITLE
Emitir declaração

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-extensao#186]
**US38 – Emitir declaração**

Eu como participante gostaria de emitir declaração para um participante da equipe de trabalho.

* A declaração deve conter as seguintes informações: nome do participante, nome da ação de extensão o qual foi participante, período de participação e nome do coordenador.
* A declaração deve conter espaço para assinatura do coordenador responsável pela ação de extensão.
* Se a declaração for emitida pelo coordenador, deve conter espaço para assinatura da direção.
* A emissão da declaração só será permitida se a ação de extensão tiver sido aprovada pelo relator.

**Comment by lucasvss** [comment]
A emissão da declaração está sendo realizada conforme o especificado só sendo emitida quando a ação é aprovada e exibindo as informações: nome do participante, nome da ação de extensão, período de participação e o nome do coordenador.

**Comment by thalita-moura** [comment]
Sugestões de melhorias:

- "Assinatura do Coordenador da Ação"

- "Assinatura do Diretor - UFC Campus de Quixadá"

- Na declaração para o coordenador, não repetir o nome do mesmo. Coloca apenas: Declaro, para os devidos fins, que o(a) participante CAMILO CAMILO ALMENDRA participou (...) como coordenador nos períodos de 01/03/2015 até 31/12/2015.

- "Nos períodos de 01/03/2015 a 31/12/2015"
