### ISSUE TITLE
Relatório de ações de extensão

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-extensao#187]
**US39 – Relatório de ações de extensão**

Eu como coordenador gostaria de visualizar relatórios de ações de extensão de acordo com o(s) filtro(s) desejado(s).

* Os filtros disponíveis são definidos por quatro tipos: ano, coordenador, situação e modalidade.
* A situação é definida por: em andamento e encerrada.
* A modalidade é definida por: programa, projeto, curso, evento e prestação de serviço.
* A busca deve ser realizada utilizando pelo menos um ou mais filtros.
* Se não houver resultados, informar que a busca não retornou nenhum resultado com os parâmetros definidos.
* O resultado do relatório deve ser um cabeçalho com os filtros da busca e uma lista contendo todas as ações de extensão de acordo com os parâmetros que foram definidos.
* Para visualizar os detalhes da ação, deve-se clicar na ação de extensão desejada.

**Comment by lucasvss** [comment]
Os filtros estão definidos como especificados.
A situação está definida como em andamento e encerrada.
A modalidade está definida como programa, projeto, curso, evento e prestação de serviço.
A busca está sendo realizada utilizando pelo menos um filtro.
Quando não há resultados está sendo informado que a busca não retornou nenhum resultado.
Está sendo exibido um cabeçalho com os filtros que foram utilizados para realizar a busca.
Quando clicado em uma ação que foi resultado da busca página é redirecionada para os detalhes da ação.

Está tudo conforme o especificado.
