### ISSUE TITLE
Transferir coordenação de uma ação de extensão

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-extensao#188]
**US33 – Transferir coordenação de uma ação de extensão**

Eu como Coordenador de uma ação de extensão gostaria de transferir a coordenação de uma ação para outro servidor, mantendo o histórico da equipe de trabalho como coordenador.

* Informar o novo coordenador, data de início e carga horária.
* A data de término será automaticamente igual à data de término da ação.
* Criar automaticamente nova participação para o novo coordenador.

**Comment by lucasvss** [comment]
Ao clicar na opção de Transferir Coordenação é exibido um modal com os campos solicitados na especificação e ao tentar transferir a coordenação da ação para um outro servidor a transferência está sendo realizada mantendo o histórico da equipe de trabalho.
