### ISSUE TITLE
Cadastrar código de ação aprovada

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-extensao#190]
**US30 – Cadastrar código de ação aprovada**

Eu como Coordenador de uma ação desejo cadastrar o código de uma ação aprovada da qual sou coordenador.

* Somente o coordenador poderá informar o código da ação.
* O código só poderá ser informado quando o status da ação for APROVADA e ainda não tiver sido encerrada.

**Comment by lucasvss** [comment]
O código prex da ação está sendo cadastrado e é mostrado na página de detalhes da ação conforme o esperado.
