### ISSUE TITLE
Solicitar resolução de pendências do parecer técnico

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-extensao#191]
**US26 – Solicitar resolução de pendências do parecer técnico**

Eu como Parecerista posso solicitar que o coordenador de uma ação de extensão resolva pendências para que seja possível emitir o parecer.

* Permitir descrever quais pendências precisam ser resolvidas.
* O status da ação deve ser alterado para RESOLVENDO PENDÊNCIAS DO PARECER TÉCNICO.
* Um email deve ser enviado para o coordenador e para o parecerista contendo as pendências a serem resolvidas.

**Comment by lucasvss** [comment]
As pendências estão sendo salvas onde o status está sendo modificado para "RESOLVENDO PENDÊNCIAS DO PARECER DO TÉCNICO" e um email é enviado tanto para o coordenador da ação quanto para o parecerista da ação.
