### ISSUE TITLE
Solicitar resolução de pendências do parecer do relator

### ISSUE THREAD

**Issue by thalita-moura** [npi-ufc-qxd/gpa-extensao#193]
**US28 – Solicitar resolução de pendências do parecer do relator**

Eu como Relator posso solicitar que o coordenador de uma ação de extensão resolva pendências para que seja possível emitir o parecer.

* Permitir descrever quais pendências precisam ser resolvidas.
* O status da ação deve ser alterado para RESOLVENDO PENDÊNCIAS DO PARECER DO RELATOR.
* Um email deve ser enviado para o coordenador e para o relator contendo as pendências a serem resolvidas.

**Comment by lucasvss** [comment]
As pendências estão sendo salvas onde o status está sendo modificado para "RESOLVENDO PENDÊNCIAS DO PARECER DO RELATOR" e um email é enviado tanto para o coordenador da ação quanto para o relator da ação.
