### ISSUE TITLE
Ajustar botões da página de detalhe da ação

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/gpa-extensao#213]
* Deixar os botões do detalhe da ação na mesma linha
* Mostrar o modal do tema ao selecionar a opção de excluir a ação
* Nas tabelas de equipe de trabalho de parcerias, colocar os botões apenas com ícones ao invés de textos.

**Comment by lucasvss** [comment]
Os botões dos detalhes da ação estão alinhados, os botões na tabela de equipe de trabalho estão com ícones conforme especificado.

Ao tentar excluir uma ação não é mostrado um modal mas sim um confirm dialog.
