### ISSUE TITLE
Informar número do processo

### ISSUE THREAD

**Issue by virginiafarias** [npi-ufc-qxd/gpa-extensao#239]
**Eu como Direção desejo informar o número do processo da ação**

* Somente o perfil de direção ou administração poderá informar o número de bolsas recebidas.
* O número de bolsas recebidas só poderá ser informado quando o status da ação for APROVADA e ainda não tiver sido encerrada.

**Comment by lucasvss** [comment]
Só é permitido a inserção de bolsas quando o usuário é da direção conforme o especificado
